module.exports = {
  env: {
    NEXT_APP_FIREBASE_KEY: process.env.NEXT_APP_FIREBASE_KEY,
    NEXT_APP_FIREBASE_DOMAIN: process.env.NEXT_APP_FIREBASE_DOMAIN,
    NEXT_APP_FIREBASE_DATABASE: process.env.NEXT_APP_FIREBASE_DATABASE,
    NEXT_APP_FIREBASE_PROJECT_ID: process.env.NEXT_APP_FIREBASE_PROJECT_ID,
    NEXT_APP_FIREBASE_STORAGE_BUCKET: process.env.NEXT_APP_FIREBASE_STORAGE_BUCKET,
    NEXT_APP_FIREBASE_SENDER_ID: process.env.NEXT_APP_FIREBASE_SENDER_ID,
    NEXT_APP_FIREBASE_APPID: process.env.NEXT_APP_FIREBASE_APPID,
    NEXT_APP_LIFF_ID: process.env.NEXT_APP_LIFF_ID,
    NEXT_APP_LIFF_CHANNEL_ACCESS_TOKEN: process.env.NEXT_APP_LIFF_CHANNEL_ACCESS_TOKEN,
    NEXT_APP_LIFF_CHANNEL_SECRET: process.env.NEXT_APP_LIFF_CHANNEL_SECRET,
  },
}
